services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5051:5000
    env_file:
      - ./.env.dev.container
    environment:
      - POSTGRES_DB_INIT=false
    deploy:
      resources:
        limits:
          cpus: '1'  # Allocate 20% of your CPU resources
          memory: 8G  # Adjust based on your free memory
    depends_on:
      - db
  db:
    build: services/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./services/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5052:5432
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
    command: postgres -c shared_buffers=512MB -c effective_io_concurrency=200 -c random_page_cost=1.1

    deploy:
      resources:
        limits:
          cpus: '3'  # Increase CPU limit (or higher if available)
          memory: 32G

volumes:
  postgres_data:
